// extension/webview/pages/Sidebar.tsx
import { useEffect, useState } from 'react';
import Button from '../components/Button';
import LoadingSpinner from '../components/LoadingSpinner';
import { useApi } from '../shared/api';
import { useAppContext } from '../context/AppContext';
import type { Page } from '../shared/types';

interface User {
  id: string;
  username: string;
  avatar: string;
  email: string;
}

interface SidebarProps {
  onPageChange?: (page: Page, params?: Record<string, any>) => void;
}

const Sidebar = ({ onPageChange }: SidebarProps) => {
  const { vscode, isAuthenticated, setPage, logout } = useAppContext();
  const { query } = useApi();
  const [isLoading, setIsLoading] = useState(true);
  const [user, setUser] = useState<User | null>(null);

  const fetchUser = async () => {
    try {
      const response = await query('/me');
      const userData = response.user || response;
      setUser(userData);
      return userData;
    } catch (error) {
      console.error('Error fetching user data:', error);
      return null;
    }
  };

  useEffect(() => {
    const loadUserData = async () => {
      if (isAuthenticated) {
        await fetchUser();
      }
      setIsLoading(false);
    };

    loadUserData();
  }, [isAuthenticated]);

  useEffect(() => {
    const messageHandler = async (event: MessageEvent) => {
      const message = event.data;

      switch (message.command) {
        case 'login-complete':
          await fetchUser();
          setIsLoading(false);
          break;
      }
    };

    window.addEventListener('message', messageHandler);
    return () => window.removeEventListener('message', messageHandler);
  }, []);

  const handleNavigate = (page: Page, params: Record<string, any> = {}) => {
    if (onPageChange) {
      onPageChange(page, params);
    } else if (setPage) {
      setPage(page);
    }
  };

  const handleExplore = () => {
    handleNavigate('explore');
  };

  const handleEditProfile = () => {
    handleNavigate('profile-form');
  };

  const handleViewMessages = () => {
    handleNavigate('messages');
  };

  if (isLoading) {
    return <LoadingSpinner />;
  }

  if (!user || !isAuthenticated) {
    return (
      <div className="p-4">
        <h2 className="text-xl font-semibold mb-4">Welcome</h2>
        <p className="mb-6 text-[color:var(--vscode-descriptionForeground)]">
          Please log in to share your code snippets and chat with your peers.
        </p>
        <div className="mb-6">
          <p className="mb-4 text-xs">
            By logging in with Google, you agree to our terms and privacy
            policy.
          </p>
        </div>
        <Button
          onClick={() => {
            console.log('Logging in');
            vscode.postMessage({ type: 'login' });
          }}
        >
          Login with Google
        </Button>
      </div>
    );
  }

  return (
    <div className="p-4">
      <div className="flex flex-col items-center p-6">
        <img
          src={user.avatar}
          alt={user.username}
          className="w-32 h-32 rounded-full mb-4 border-2 border-[color:var(--vscode-button-background)]"
        />

        <h1 className="text-xl font-semibold mb-1">{user.username}</h1>
        <p className="text-sm text-[color:var(--vscode-descriptionForeground)] mb-6">
          {user.email}
        </p>

        <div className="w-full space-y-3">
          <Button onClick={handleEditProfile} className="w-full">
            Edit Profile
          </Button>
          <Button onClick={handleViewMessages} className="w-full">
            Messages
          </Button>
          <Button onClick={handleExplore} className="w-full">
            Explore
          </Button>
          <Button appearance="secondary" onClick={logout} className="w-full">
            Logout
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Sidebar;

// extension/webviews/components/Sidebar.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { query } from "../shared/query";
  import type { State, User } from "../shared/types";
  import Profile from "../screens/Profile.svelte";
  import LoadingSpinner from "../ui/LoadingSpinner.svelte";
  import EditProfile from "../screens/EditProfile.svelte";
  import Explore from "../screens/Explore.svelte";
  import Messages from "../screens/Messages.svelte";
  import Conversation from "../screens/Conversation.svelte";

  let gotTokens = false;
  let currentUserIsLoading: boolean = true;
  let currentUser: User | null = null;
  let lastState = vscode.getState();

  let state: State = { page: "loading" };

  async function fetchUser() {
    if (!accessToken || !refreshToken) {
      return;
    }
    try {
      const r = await query("/me");
      currentUser = r.user;
      return r.user;
    } catch {}
  }

  function redirectUser(u?: User | null) {
    if (u) {
      state = { page: "view-profile" };
    } else {
      state = { page: "login" };
    }
  }

  function userToInitialFormData(u: User) {
    return {
      username: u.username,
      avatar: u.avatar,
      email: u.email,
    };
  }

  function goToEditForm() {
    if (currentUser) {
      state = {
        page: "profile-form",
        data: userToInitialFormData(currentUser),
      };
    }
  }

  onMount(async () => {
    vscode.postMessage({ type: "send-tokens" });
  });

  $: {
    vscode.setState(state);
  }

  window.addEventListener("message", async (event) => {
    const message = event.data;

    switch (message.command) {
      case "init-tokens":
        accessToken = message.payload.accessToken;
        refreshToken = message.payload.refreshToken;
        gotTokens = true;
        try {
          const u = await fetchUser();
          if (state.page === "loading") {
            redirectUser(u);
          } else if (!u) {
            state = { page: "login" };
          }
        } catch {}
        currentUserIsLoading = false;
        break;
      case "login-complete":
        accessToken = message.payload.accessToken;
        refreshToken = message.payload.refreshToken;
        fetchUser().then((u) => {
          redirectUser(u);
        });
        break;
    }
  });
</script>

{#if state.page === "loading"}
  <LoadingSpinner />
{:else if state.page === "login"}
  <div style="margin-bottom: 40px;">
    By tapping login with Google, you agree to our terms and privacy
  </div>
  <button
    on:click={() => {
      vscode.postMessage({ type: "login" });
    }}>Login with Google to get started</button
  >
{:else if state.page === "view-profile"}
  <Profile
    {currentUser}
    {currentUserIsLoading}
    onEditProfile={() => {
      goToEditForm();
    }}
    onExplore={() => {
      state = { page: "explore" };
    }}
    onLogout={() => {
      state = { page: "login" };
      currentUser = null;
    }}
    onViewMessages={() => {
      state = { page: "conversation" };
    }}
  />
{:else if state.page === "profile-form"}
  <EditProfile
    onNewState={(s) => {
      state = s;
    }}
    bind:data={state.data}
    onUpdate={() => {}}
  />
{:else if state.page === "explore"}
  <Explore
    onNewState={(s) => {
      state = s;
    }}
  />
{:else if state.page === "conversation"}
  <Conversation
    bind:currentUser
    {currentUserIsLoading}
    bind:state
    onNewState={(s) => {
      state = s;
    }}
  />
{/if}

<style>
  p {
    color: yellow;
  }
</style>
